# Generated by Django 4.0.4 on 2022-04-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('dni', models.IntegerField(default=0)),
                ('teléfono', models.IntegerField(default=0)),
                ('dirección', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nac', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
