# Generated by Django 4.0.4 on 2022-04-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_cliente_fecha_nac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Clategoria',
        ),
    ]
